### ISSUE TITLE
How to call API methods created by plugins?

### ISSUE THREAD

**Issue by pgasior** [jeffka11/ttrss_api#1]
TT-RRS allows plugins to create new API methods. Is it possible to call such methods with this crate?
It would probably work if `request_from_api` was public.

**Comment by jeffka11** [comment]
Hi, thanks @pgasior for the suggestion and your patience since it took a while for me to get to this comment. I fixed this in v0.2.1 with your suggestion of making `request_from_api` public. I'm closing this now since it's fixed, please comment if you have issues.
